const TEACHER_DEFAULT = "none";

const STATUSES = {
	LEAD: "LEAD",
	TRIAL_LESSON: "TRIAL_LESSON",
	STUDY: "STUDY",
	ONHOLD: "ONHOLD",
	WAITING_FOR_PAYMENT: "WAITING_FOR_PAYMENT",
};

const ROLES = {
	STUDENT: "STUDENT",
	TEACHER: "TEACHER",
	ADMIN: "ADMIN",
	USER: "USER",
};

module.exports = {
	TEACHER_DEFAULT,
	STATUSES,
	ROLES,
};
